### ISSUE TITLE
Publish-DSCPullResources doesn't work with versioned module install directories?

### ISSUE THREAD

**Issue by ljharper** [PlagueHO/DSCTools#5]
It appears the 'Publish-DSCPullResources' doesn't work with 'versioned' module install directories.  I'm not real up on PowerShell history, but when you install modules with PowerShell Get (install-module), they end up in a versioned directory (e.g.  C:\Program Files\WindowsPowerShell\Modules\SharePointDSC\1.8.0.0\ ) and the commandlet seems confused by the '1.8.0.0' directory.

I could certainly be missing an easy workaround, as I'm not real familiar with any of this.

Otherwise, if the command needs to be updated, I'd be happy to take a shot at it if you'd give me a bit of guidance as to how you'd like it done.  Should all versions found be published, or only the latest version?  Add a new flag?

Thanks!

**Comment by PlagueHO** [comment]
Hi @ljharper - thank you for bringing this to my attention! I'll take a look and issue a fix.

**Comment by PlagueHO** [comment]
Hi @ljharper - I've released a new version of this Module to PSGallery that should fix this problem:
https://www.powershellgallery.com/packages/DSCTools/1.8.0.31

Thanks
